# Generated by Django 5.2.5 on 2025-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetable'), ('FRUIT', 'Fruit')], default='grocery', max_length=20),
            preserve_default=False,
        ),
    ]
